package com.example.sqlparser.model.postgresql;

import lombok.Data;

/**
 * PostgreSQL 列定义
 */
@Data
public class PostgreSQLColumnDef {
    
    // 基础属性
    private String name;
    private String dataType;
    private boolean nullable = true;
    private String comment;
    
    // PostgreSQL 特有属性
    private boolean serial;           // SERIAL, BIGSERIAL
    private boolean generated;        // GENERATED ALWAYS AS / GENERATED BY DEFAULT
    private String generationExpression;  // 生成列表达式
    private String collation;         // COLLATE
    private String compression;       // COMPRESSION
    private String storage;           // STORAGE (PLAIN, EXTERNAL, EXTENDED, MAIN)
    
    // 数组类型
    private boolean array;
    private int arrayDimensions;
    
    // 约束
    private boolean primaryKey;
    private boolean unique;
    private String check;
    private String references;        // 外键引用
    private String onDelete;
    private String onUpdate;
    
    // 默认值
    private boolean defaultNull;
    private String defaultExpression;
    
    // 标识列 (PostgreSQL 10+)
    private boolean identity;         // GENERATED ALWAYS AS IDENTITY
    private String identityOptions;   // 身份列选项
}
